---
  clickhouse:
    hosts:
      clickhouse-01:
        ansible_host: 51.250.90.59
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: '~/.ssh/id_ed25519'
        
  vector:
    hosts:
      vector-01:
        ansible_host: 51.250.79.252
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: '~/.ssh/id_ed25519'

  lighthouse:
    hosts:
      lighthouse-01:
        ansible_host: 51.250.64.222
        ansible_ssh_user: centos
        ansible_ssh_private_key_file: '~/.ssh/id_ed25519'